# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15fc8e411a698b539c5cfd5d44237588443ac89c27769a4300667d12c6d9d130f9290ff6d63745950d52127aa5c7e498977253422ac2192fbc482e11afc0faa7

test:
  secret_key_base: 2e7e8e6232e12734705924456112a8e92cf8fc832ef0e822519b4ca07a3d7918c8de6f0082db685c7591ab6c080a52c7c1a887882ba9e29d526482eccc967aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
